apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-demo1
  namespace: default
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template: ## pod 配置
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80