apiVersion: v1
kind: Pod
metadata:
  name: dapi-pod-file
  labels:
    zone: hangzhou
    env: test
  annotations:
    test: test
spec:
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
  containers:
  - name: dapi
    image: busybox
    command: ["sh", "-c"]
    args:
    - while true; do 
        if [[ -e /etc/podinfo/labels ]]; then
          echo -en '\n\n'; cat /etc/labels; fi;
        if [[ -e /etc/podinfo/annotations ]]; then
          echo -en '\n\n'; cat /etc/annotations; fi;
        sleep 3600;
      done;
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 100Mi
        cpu: 100m
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo