apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  volumes:
  - name: workdir
    emptyDir: {}
  initContainers:
  - name: init-container-demo
    image: busybox
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - http://www.baidu.com
    volumeMounts:
    - name: workdir
      mountPath: /work-dir
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html