apiVersion: v1
kind: Pod
metadata:
  name: livenessprobe-tcp
spec:
  containers:
  - name: liveness
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 15