apiVersion: v1
kind: Pod
metadata:
  name: poststart-hook
spec:
  containers:
  - name: hook-demo
    image: nginx
    command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]